First we import <b>Library</b>

## 1.Patient_diet Case Study

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
%matplotlib inline

In [2]:
diet = pd.read_csv("dietstudy.csv")
diet.head()

patid  age  gender  tg0  tg1  tg2  tg3  tg4  wgt0  wgt1  wgt2  wgt3  wgt4
0      1   45    Male  180  148  106  113  100   198   196   193   188   192
1      2   56    Male  139   94  119   75   92   237   233   232   228   225
2      3   50    Male  152  185   86  149  118   233   231   229   228   226
3      4   46  Female  112  145  136  149   82   179   181   177   174   172
4      5   64    Male  156  104  157   79   97   219   217   215   213   214

In [7]:
diet.isnull().any().sum()

0

So here is no any null values

### Paired T-test sample

In [5]:
# Test for triglyceride after 6 months
print(stats.ttest_rel(a=diet.tg0,b=diet.tg4))

Ttest_relResult(statistic=1.2000008533342437, pvalue=0.24874946576903698)


In [6]:
# Test for Weight after 6 months
print(stats.ttest_rel(a=diet.wgt0,b=diet.wgt4))

Ttest_relResult(statistic=11.174521688532522, pvalue=1.137689414996614e-08)


<h3>Conclusion: </h3> <i>The <b>successfull</b> measurement applied by the physician to the patients is </i><br>
    - It doesn't affect in the <b>triglyceride</b> but<br>
    - It  <b>increase theweight</b> of each patient

# 2.Credit card Case Study

In [8]:
credit = pd.read_csv('creditpromo.csv')
credit.head()

id         insert      dollars
0   148       Standard  2232.771979
1   572  New Promotion  1403.807542
2   973       Standard  2327.092181
3  1096       Standard  1280.030541
4  1541  New Promotion  1513.563200

In [9]:
std = credit.dollars[credit['insert'] == 'Standard']
std.head()

0    2232.771979
2    2327.092181
3    1280.030541
7    1476.624884
8    1460.769753
Name: dollars, dtype: float64

In [10]:
promo = credit.dollars[credit['insert'] == 'New Promotion']
print(promo.head())

1    1403.807542
4    1513.563200
5    1729.627996
6    1609.705918
9    1854.489028
Name: dollars, dtype: float64


##### (Independent) Two-Sample T-test

In [12]:
stats.ttest_ind(a = std, 
                b = promo, 
                equal_var=False )


Ttest_indResult(statistic=-2.2604227260537053, pvalue=0.024226348217341587)

<h3>Conclusion: </h3>Yes It works, the new idea evaluated by the department to increased sales is absolutely work.<br>
<i>The survey conducted on the <b>ad promoting</b> is more than the <b>standard seasonal ad</b></i>


# 3.Pollination Case Study

In [14]:
poll = pd.read_csv('pollination.csv')
poll.head()

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90

In [15]:
# Q3.1-------------------------
# H0: mean=200
# H1: mean <> 200
x=poll['Seed_Yield_Plant']
stats.ttest_1samp(a=x,popmean=200)


Ttest_1sampResult(statistic=-2.3009121248548645, pvalue=0.032891040921283025)

<h3>Conclusion: </h3> Overall population of seed plant is not equal to <b>200</b>

In [16]:
Nature = poll[poll.Group == 'Natural'].reset_index(drop=True)
Hand = poll[['Group','Fruit_Wt','Seed_Yield_Plant','Seedling_length']][poll.Group == 'Hand'].reset_index(drop=True)

In [17]:
Nature

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90
5  Natural      1.88            138.30            16.95
6  Natural      1.89            150.58            18.15
7  Natural      1.79            140.99            18.86
8  Natural      1.85            140.57            18.39
9  Natural      1.84            138.33            18.58

In [18]:
Hand

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Hand      2.58            224.26            18.18
1  Hand      2.74            197.50            18.07
2  Hand      2.58            230.34            19.07
3  Hand      2.62            217.05            19.00
4  Hand      2.68            233.84            18.00
5  Hand      2.56            216.52            18.49
6  Hand      2.34            211.93            17.45
7  Hand      2.67            210.37            18.97
8  Hand      2.45            199.87            19.31
9  Hand      2.44            214.30            19.36

In [19]:
# Compaired Fruit Weight
stats.ttest_ind(a = Nature['Fruit_Wt'],
                b = Hand['Fruit_Wt'])

Ttest_indResult(statistic=-17.669989614440286, pvalue=8.078362076486221e-13)

In [20]:
# Compaired Seed_Yield_Plant
stats.ttest_ind(a = Nature['Seed_Yield_Plant'],
                b = Hand['Seed_Yield_Plant'])

Ttest_indResult(statistic=-13.958260515902547, pvalue=4.2714815854843853e-11)

In [21]:
# Compaired Seedling_length
stats.ttest_ind(a = Nature['Seedling_length'],
                b = Hand['Seedling_length'])

Ttest_indResult(statistic=-2.542229999657055, pvalue=0.020428817064110226)

<h3>Conclusion: </h3> The experiment applied on hybrid seed production using <b>Hand Pollination</b> is not effectivelly than <b> Nature Pollination</b>

# 4.DvD Player Age

In [22]:
dvd = pd.read_csv('dvdplayer.csv')
dvd.head(10)

agegroup   dvdscore
0  65 and over  38.454803
1        55-64  17.669677
2  65 and over  31.704307
3  65 and over  25.924460
4     Under 25  30.450007
5     Under 25  35.609909
6  65 and over  29.677695
7        25-34  38.167369
8  65 and over  23.509700
9        45-54  26.051029

In [23]:
d0 = dvd['dvdscore'][dvd.agegroup == 'Under 25'].reset_index(drop=True)
d1 = dvd['dvdscore'][dvd.agegroup == '25-34'].reset_index(drop=True)
d2 = dvd['dvdscore'][dvd.agegroup == '35-44'].reset_index(drop=True)
d3 = dvd['dvdscore'][dvd.agegroup == '45-54'].reset_index(drop=True)
d4 = dvd['dvdscore'][dvd.agegroup == '55-64'].reset_index(drop=True)
d5 = dvd['dvdscore'][dvd.agegroup == '65 and over'].reset_index(drop=True)
print("size of each Age Group:"
      "\nUnder 25:(",d0.size,")\t\t25-34:(",d1.size,")\t35-44:(",d2.size,
      ")\t45-54:(",d3.size,")\t55-64:(",d4.size,")\t65 and Over:(",d5.size,")")

size of each Age Group:
Under 25:( 13 )		25-34:( 10 )	35-44:( 12 )	45-54:( 10 )	55-64:( 6 )	65 and Over:( 17 )


In [24]:
stats.f_oneway(d0,d1,d2,d3,d4,d5)

F_onewayResult(statistic=6.992526962676518, pvalue=3.087324905679639e-05)

<h3>Conclusion: </h3> <i>consumers  of  various  ages  rated  the  design <b><i>differently</i></b></i>

# 5.Sample Survey

In [25]:
pd.set_option("display.max_row",100)
data = pd.read_csv("sample_survey.csv")
data.head()

id            wrkstat        marital  childs   age  educ  paeduc  maeduc  \
0   1  Working full time       Divorced     2.0  60.0  12.0    12.0    12.0   
1   2  Working part-time  Never married     0.0  27.0  17.0    20.0     NaN   
2   3  Working full time        Married     2.0  36.0  12.0    12.0    12.0   
3   4  Working full time  Never married     0.0  21.0  13.0     NaN    12.0   
4   5  Working full time  Never married     0.0  35.0  16.0     NaN    12.0   

   speduc          degree    ...           agecat childcat news1 news2  news3  \
0     NaN     High school    ...         55 to 64    2-Jan    No    No     No   
1     NaN  Junior college    ...         25 to 34     None    No    No    Yes   
2    16.0     High school    ...         35 to 44    2-Jan    No    No     No   
3     NaN     High school    ...     Less than 25     None    No    No     No   
4     NaN        Bachelor    ...         35 to 44     None    No    No     No   

  news4 news5      car1      car2      car3  
0    No    No  American  Japanese  Japanese  
1    No    No  American    German  Japanese  
2   Yes   Yes  American  American       NaN  
3   Yes   Yes  American     Other       NaN  
4    No    No  American  American    Korean  

[5 rows x 46 columns]

In [27]:
# Q5.1------------------
# H0: wrkstat != martial
# H1: wrkstat == martial
#data.head()
t1=pd.crosstab(data.wrkstat,data.marital,margins =True)
t1
# we reject the null hypothesis as p<5 %, Yes both are significantly related

marital                  Divorced  Married  Never married  Separated  Widowed  \
wrkstat                                                                         
Keeping house                  25      200             35         13       55   
Other                          12       16             14          4        8   
Retired                        53      168             17          6      150   
School                          7        9             60          2        1   
Temporarily not working         9       23             11          1        2   
Unemployed, laid off           10       13             32          0        3   
Working full time             295      778            392         58       44   
Working part-time              35      138            102          9       20   
All                           446     1345            663         93      283   

marital                   All  
wrkstat                        
Keeping house             328  
Other                      54  
Retired                   394  
School                     79  
Temporarily not working    46  
Unemployed, laid off       58  
Working full time        1567  
Working part-time         304  
All                      2830

In [28]:
stats.chi2_contingency(t1)

(729.2421426572284,
 1.820339965538765e-127,
 40,
 array([[5.16918728e+01, 1.55886926e+02, 7.68424028e+01, 1.07787986e+01,
         3.28000000e+01, 3.28000000e+02],
        [8.51024735e+00, 2.56643110e+01, 1.26508834e+01, 1.77455830e+00,
         5.40000000e+00, 5.40000000e+01],
        [6.20932862e+01, 1.87254417e+02, 9.23045936e+01, 1.29477032e+01,
         3.94000000e+01, 3.94000000e+02],
        [1.24501767e+01, 3.75459364e+01, 1.85077739e+01, 2.59611307e+00,
         7.90000000e+00, 7.90000000e+01],
        [7.24946996e+00, 2.18621908e+01, 1.07766784e+01, 1.51166078e+00,
         4.60000000e+00, 4.60000000e+01],
        [9.14063604e+00, 2.75653710e+01, 1.35879859e+01, 1.90600707e+00,
         5.80000000e+00, 5.80000000e+01],
        [2.46954770e+02, 7.44740283e+02, 3.67109894e+02, 5.14950530e+01,
         1.56700000e+02, 1.56700000e+03],
        [4.79095406e+01, 1.44480565e+02, 7.12197880e+01, 9.99010601e+00,
         3.04000000e+01, 3.04000000e+02],
        [4.46000000e+02, 1.345

<h3>Conclusion: </h3><i>yes, relationship between labour force status with marital status are significantly related</i>

In [29]:
# Q5.2------------------
# H0: educational qulaifiaction != martial
# H1: educational qulaifiaction  == martial
#data.head()
t2=pd.crosstab(data.degree,data.marital,margins =True)
t2
# we reject the null hypothesis as p<5 %, Yes both are significantly related

marital         Divorced  Married  Never married  Separated  Widowed   All
degree                                                                    
Bachelor              58      251            129         12       28   478
Graduate              29      123             41          3        9   205
High school          241      686            367         58      148  1500
Junior college        45      108             46          3        6   208
LT High school        70      174             77         17       92   430
All                  443     1342            660         93      283  2821

In [30]:
stats.chi2_contingency(t2)

(122.68449020508541,
 7.424404099753273e-15,
 25,
 array([[  75.06345268,  227.39312301,  111.83268345,   15.75824176,
           47.95249911,  478.        ],
        [  32.19248493,   97.52215526,   47.9617157 ,    6.75824176,
           20.56540234,  205.        ],
        [ 235.55476781,  713.57674583,  350.9393832 ,   49.45054945,
          150.4785537 , 1500.        ],
        [  32.66359447,   98.94930876,   48.66359447,    6.85714286,
           20.86635945,  208.        ],
        [  67.52570011,  204.55866714,  100.60262318,   14.17582418,
           43.1371854 ,  430.        ],
        [ 443.        , 1342.        ,  660.        ,   93.        ,
          283.        , 2821.        ]]))

<h3>Conclusion: </h3><i>Yes, educational qualification  is significantly related for controlling the marital status</i>

In [31]:
# Q5.3.1------------------
# H0: happy != martial
# H1: happy  == martial
#data.head()
t3=pd.crosstab(data.happy,data.marital,margins =True)
t3
# we reject the null hypothesis as p<5 %, Yes both are significantly related

marital        Divorced  Married  Never married  Separated  Widowed   All
happy                                                                    
Not too happy        72       71            108         30       59   340
Pretty happy        278      684            426         49      137  1574
Very happy           93      582            120         13       83   891
All                 443     1337            654         92      279  2805

In [ ]:
stats.chi2_contingency(t3)

In [26]:
# Q5.3.2------------------
# H0: happy != income
# H1: happy  == income
#data.head()
t4=pd.crosstab(data.happy,data.income,margins =True)
stats.chi2_contingency(t4)
# we reject the null hypothesis as p<5 %, Yes both are significantly related

(178.95053061216427,
 7.234749067043371e-21,
 36,
 array([[   3.89520355,   23.12777106,   21.66706973,   29.82265216,
          191.35187424,    2.92140266,    3.89520355,    4.26037888,
            4.01692866,    5.72108021,    7.06005643,    4.26037888,
          302.        ],
        [  18.16041919,  107.82748892,  101.01733172,  139.04070939,
          892.1305925 ,   13.62031439,   18.16041919,   19.86295848,
           18.72793229,   26.67311568,   32.91575977,   19.86295848,
         1408.        ],
        [   9.94437727,   59.04474002,   55.31559855,   76.13663845,
          488.51753325,    7.45828295,    9.94437727,   10.87666264,
           10.25513906,   14.60580411,   18.0241838 ,   10.87666264,
          771.        ],
        [  32.        ,  190.        ,  178.        ,  245.        ,
         1572.        ,   24.        ,   32.        ,   35.        ,
           33.        ,   47.        ,   58.        ,   35.        ,
         2481.        ]]))

<h3>Conclusion: </h3> <i> Here <b>happiness</b> is driven by both earnings and marital status </i>